#!/bin/bash

FIRSTNAMES_F='data/first-names-female'
FIRSTNAMES_M='data/first-names-male'
LASTNAMES='data/last-names'
PLACES='data/places.csv'
SUFFIXES='data/suffixes'

DB='two-one.db'
SQLITE=sqlite3

[ -e $DB ] && rm $DB

$SQLITE $DB ".mode csv" ".import $FIRSTNAMES_F firstnames"
$SQLITE $DB ".mode csv" ".import $FIRSTNAMES_M firstnames"
$SQLITE $DB ".mode csv" ".import $LASTNAMES    lastnames"
$SQLITE $DB ".mode csv" ".import $SUFFIXES     suffixes"
$SQLITE $DB ".mode csv" ".import $PLACES       temp"

$SQLITE $DB <<EOF
.mode csv

CREATE TABLE places
AS
SELECT DISTINCT(name)
FROM temp
WHERE country='England'
AND LENGTH(name) <= 12;

DROP TABLE temp;

VACUUM;
EOF

$SQLITE $DB <<EOF
SELECT "firstnames", COUNT(*) FROM firstnames;
SELECT "lastnames",  COUNT(*) FROM lastnames;
SELECT "places",     COUNT(*) FROM places;
SELECT "suffixes",   COUNT(*) FROM suffixes;
EOF
